
server:
  address:
  port: 8081
  servlet:
    context-path: /workProcess

spring:
  application:
    name: rgkCloud-IoT-process
  datasource:
    type:
    url: jdbc:mysql://localhost:3306/rgkcloud-iot-process?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  activiti:
    check-process-definitions: false
    history-level: full
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  main:
    allow-bean-definition-overriding: true


eureka:
  client:
    service-url:
      defaultZone: http://192.168.160.33:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      client-id: workflow
      client-secret: 123
      access-token-uri: http://192.168.160.33:8080/oauth/token
      user-authorization-uri: http://192.168.160.33:8080/oauth/authorize
    resource:
      token-info-uri: http://192.168.160.33:8080/oauth/check_token
      user-info-uri: http://192.168.160.33:8080/user/info
  basic:
    enabled: false

